// <auto-generated />
using Medical.data.EF;
using Medical.data.EF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Medical.data.EF.Migrations
{
    [DbContext(typeof(EfUnitOfWork))]
    [Migration("20180215111508_AuthRoles2")]
    partial class AuthRoles2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Medical.data.EF.Models.ContactDbModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("NamePhoneOwner");

                    b.Property<long>("PatientId");

                    b.Property<string>("Phone");

                    b.Property<string>("Relation");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Medical.data.EF.Models.PatientDbModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<DateTime>("DateIssuePassport");

                    b.Property<DateTime>("DateTimeRigist");

                    b.Property<string>("FirstName");

                    b.Property<int>("Gender");

                    b.Property<string>("LastName");

                    b.Property<string>("PassportNumber");

                    b.Property<string>("PlaceIssuePassport");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Medical.data.EF.Models.RoleDbModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Medical.data.EF.Models.SpecialtyDbModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Specialties");
                });

            modelBuilder.Entity("Medical.data.EF.Models.UserDbModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Age");

                    b.Property<string>("Gender");

                    b.Property<string>("Login");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<long?>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Medical.data.EF.Models.ContactDbModel", b =>
                {
                    b.HasOne("Medical.data.EF.Models.PatientDbModel", "Patient")
                        .WithMany("Contacts")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Medical.data.EF.Models.SpecialtyDbModel", b =>
                {
                    b.HasOne("Medical.data.EF.Models.UserDbModel", "User")
                        .WithMany("Specialties")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Medical.data.EF.Models.UserDbModel", b =>
                {
                    b.HasOne("Medical.data.EF.Models.RoleDbModel", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");
                });
#pragma warning restore 612, 618
        }
    }
}
